name: "Post release"
on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  update-gha-assets:
    name: "Update readme"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Update GitHub Action config
        run: date -u '+%Y-%m-%d_%H:%M:%S' >> README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          base: main
          token: ${{ secrets.BOT_TOKEN }}
          author: GolangCI-Lint Releaser <65486276+golangci-releaser@users.noreply.github.com>
          push-to-fork: golangci-releaser/fictional-umbrella
          branch-suffix: timestamp
          title: "docs: update readme"
          delete-branch: true
